### PR TITLE
Update to Polymer 1.0

### PR DESCRIPTION
**Pull request by adalinesimonian**
I'll be the first to say that if y'all weren't planning on moving `flatiron-director` to 0.9, I won't be taken aback by a "no thanks." :smile: I'm not all that familiar with git just yet (I'm moving to using git primarily from a background of working with SVN) so I don't know if there's a way to submit a pull request for a new branch.. or if I'm doing it right by submitting this PR as-is. (I created a 0.9 branch on my fork when working on the element).

Now, about the actual changes:
- Converted element to Polymer 0.9
- Reorganized directory structure/files to match the rest of the 0.9 series elements from the Polymer team
- Updated Polymer project copyright notice header to latest version present in other element repos
- Updated version in bower.json to 0.9.0
- Added unit tests (currently passes all tests in Safari 8, Chrome 42, Firefox 37 on OS X)
- Updated Flatiron Director to 1.2.6 from 1.2.2
- Modified global variable behaviour to be a tad more solid
- Added basic documentation (adapted from [Polymer 0.5 SPA tutorial](https://www.polymer-project.org/0.5/articles/spa.html))

Cheers! :beers:

### CODE REVIEW

**Comment by addyosmani** [comment]
This appears to be a bit more comprehensive of a port compared to #9 and includes tests. Unfortunately it's still using 0.9 rather than 1.0. Are you interested in updating this PR? If so, we can go ahead here. If not, we can close and focus on the 1.0 port that doesn't include tests. Any interest?

**Comment by vsimonian** [comment]
I'd be more than glad to update this for 1.0. Shouldn't take very long!

**Comment by vsimonian** [comment]
@addyosmani I updated it to 1.0, and fixed a few things I hadn't noticed before. Hope it's looking good now!

**Comment by jhabdas** [comment]
Sounds like a merge to me. Patch releases are of little concern. ^0.7.0 out to do it, right @addyosmani?

**Comment by kungufli** [comment]
Sounds good to me, anyone can merge this please?

**Comment by gaurav21r** [comment]
+1 :+1:

**Comment by samccone** [comment]
@addyosmani looks good to me and is working (:

**Comment by addyosmani** [comment]
LGTM. Apologies for the delay on this one.

**Pull request merged**
